import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Link shortener",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased text-[14px] text-[#0D141C]`}>
        {children}
      </body>
    </html>
  );
}
